name: nebula
description: "a mail client written in flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  bitsdojo_window: ^0.1.6
  mailer: ^6.1.2
  enough_mail: ^2.1.6
  intl: ^0.19.0
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
